name       : jp2a
version    : 1.0.7
release    : 3
source     :
    - https://github.com/cslarsen/jp2a/archive/v1.0.7.tar.gz : e509d8bbf9434afde5c342568b21d11831a61d9942ca8cb1633d4295b7bc5059
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : jp2a is a simple JPEG to ASCII converter
description: |
    jp2a is a simple JPEG to ASCII converter
builddeps  :
    - libjpeg-turbo-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
